services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    environment:
      - TZ=${TZ}
    command:
      - "--path.rootfs=/host"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|rootfs|var/lib/docker/.+|var/lib/kubelet/.+)($$|/)"
      - "--collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$$"
      - "--web.listen-address=${TS_IP}:9100"
    volumes:
      - "/:/host:ro,rslave"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ}
    cap_add:
      - NET_RAW
    command:
      - "--config.file=/etc/blackbox_exporter/blackbox.yml"
      - "--web.listen-address=${TS_IP}:9115"
    volumes:
      - "./blackbox/blackbox.yml:/etc/blackbox_exporter/blackbox.yml:ro"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.2
    container_name: cadvisor
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - TZ=${TZ}
    command:
      - "--listen_ip=${TS_IP}"
      - "--port=8080"
      - "--docker_only=true"
      - "--housekeeping_interval=15s"
      - "--disable_metrics=disk,percpu,sched,tcp,udp,advtcp,process,hugetlb,referenced_memory,cpu_topology,resctrl"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ}
      - TS_IP=${TS_IP}
      - ENVIRONMENT=${ENVIRONMENT}
      - NODE_NAME=${NODE_NAME}
      - LOKI_PUSH_URL=${LOKI_PUSH_URL}
    command:
      - "-config.file=/etc/promtail/config.yml"
      - "-config.expand-env=true"
    volumes:
      - "./promtail/config.yml:/etc/promtail/config.yml:ro"
      - "./data/promtail:/var/lib/promtail"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
