auth_enabled: false

server:
  http_listen_address: ${MONITOR_TS_IP}
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /var/lib/loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-04-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /var/lib/loki/chunks

compactor:
  working_directory: /var/lib/loki/compactor
  retention_enabled: true
  delete_request_store: filesystem

limits_config:
  retention_period: ${LOKI_RETENTION}
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_query_lookback: ${LOKI_RETENTION}
