#!/usr/bin/env bash
# Setup script for the central monitoring server.
# On first run: interactively prompts for configuration and writes .env.
# On subsequent runs: loads existing .env and skips prompts.
set -euo pipefail

cd "$(dirname "$0")"

# ── Helpers ───────────────────────────────────────────────────────────────────

ask() {
  # ask <VAR_NAME> <prompt> [default]
  local var="$1" prompt="$2" default="${3:-}"
  local value=""
  if [[ -n "$default" ]]; then
    read -rp "${prompt} [${default}]: " value
    value="${value:-$default}"
  else
    while [[ -z "$value" ]]; do
      read -rp "${prompt}: " value
    done
  fi
  printf -v "$var" '%s' "$value"
}

ask_secret() {
  # ask_secret <VAR_NAME> <prompt>
  local var="$1" prompt="$2"
  local value="" confirm=""
  while true; do
    read -rsp "${prompt}: " value; echo
    read -rsp "Confirm password: " confirm; echo
    if [[ "$value" == "$confirm" ]]; then
      break
    fi
    echo "  Passwords do not match, try again."
  done
  printf -v "$var" '%s' "$value"
}

write_env() {
  cat > .env <<EOF
# Generated by setup.sh — edit as needed.
# This file is NOT committed to git.

TZ=${TZ}
GF_ADMIN_USER=${GF_ADMIN_USER}
GF_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
DOMAIN=${DOMAIN}
PROMETHEUS_RETENTION=${PROMETHEUS_RETENTION}
EOF
  echo "  Written to .env"
}

# ── 1. .env: create interactively on first run, load on subsequent runs ───────

if [[ ! -f .env ]]; then
  echo "========================================"
  echo "  First-time setup — configure .env"
  echo "========================================"
  echo ""

  ask TZ            "Timezone for all containers"              "Asia/Shanghai"
  ask GF_ADMIN_USER "Grafana admin username"                   "admin"
  ask_secret GF_ADMIN_PASSWORD "Grafana admin password"
  ask DOMAIN        "Grafana public domain (e.g. monitor.example.com)"
  ask PROMETHEUS_RETENTION "Prometheus data retention"         "30d"

  echo ""
  write_env
  echo ""
else
  echo "==> Loading existing .env"
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

# ── 2. Runtime data directories ───────────────────────────────────────────────
echo "==> Creating runtime data directories..."
mkdir -p data/prometheus data/alertmanager grafana/data

echo "==> Fixing Grafana data directory permissions (UID 472)..."
sudo chown -R 472:472 grafana/data
sudo chmod -R u+rwX grafana/data

# ── 3. Prometheus target files ────────────────────────────────────────────────
echo "==> Generating Prometheus target files..."
chmod +x gen-targets.sh
./gen-targets.sh

# ── 4. Done ───────────────────────────────────────────────────────────────────
echo ""
echo "==> Setup complete. Next steps:"
echo ""
echo "    1. Edit servers.txt — add your Tailscale nodes"
echo "    2. Edit probes/http_targets.txt, icmp_targets.txt, tcp_targets.txt"
echo "       then re-run: ./gen-targets.sh"
echo "    3. Configure Nginx using the example in nginx/monitor.conf"
echo "       Replace 'monitor.example.com' with your actual domain"
echo "    4. Run: docker compose up -d"
echo "    5. Run: docker exec prometheus promtool check config /etc/prometheus/prometheus.yml"
