#!/usr/bin/env bash
# Setup script for the central monitoring server.
# On first run: interactively prompts for configuration and writes .env.
# On subsequent runs: loads existing .env and skips prompts.
set -euo pipefail

cd "$(dirname "$0")"

# ── Helpers ───────────────────────────────────────────────────────────────────

ask() {
  # ask <VAR_NAME> <prompt> [default]
  local var="$1" prompt="$2" default="${3:-}"
  local value=""
  if [[ -n "$default" ]]; then
    read -rp "${prompt} [${default}]: " value
    value="${value:-$default}"
  else
    while [[ -z "$value" ]]; do
      read -rp "${prompt}: " value
    done
  fi
  printf -v "$var" '%s' "$value"
}

ask_secret() {
  # ask_secret <VAR_NAME> <prompt>
  local var="$1" prompt="$2"
  local value="" confirm=""
  while true; do
    read -rsp "${prompt}: " value; echo
    read -rsp "Confirm password: " confirm; echo
    if [[ "$value" == "$confirm" ]]; then
      break
    fi
    echo "  Passwords do not match, try again."
  done
  printf -v "$var" '%s' "$value"
}

set_env_value() {
  # set_env_value <KEY> <VALUE>
  local key="$1" value="$2"
  if [[ -f .env ]] && grep -q "^${key}=" .env; then
    sed -i "s|^${key}=.*|${key}=${value}|" .env
  else
    printf '%s=%s\n' "$key" "$value" >> .env
  fi
}

write_env() {
  cat > .env <<EOF
# Generated by setup.sh — edit as needed.
# This file is NOT committed to git.

TZ=${TZ}
GF_ADMIN_USER=${GF_ADMIN_USER}
GF_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
DOMAIN=${DOMAIN}
PROMETHEUS_RETENTION=${PROMETHEUS_RETENTION}
MONITOR_TS_IP=${MONITOR_TS_IP}
LOKI_MODE=${LOKI_MODE}
LOKI_URL=${LOKI_URL}
LOKI_RETENTION=${LOKI_RETENTION}
EOF
  echo "  Written to .env"
}

if ! command -v tailscale &>/dev/null; then
  echo "ERROR: tailscale is not installed or not in PATH."
  exit 1
fi

MONITOR_TS_IP=$(tailscale ip -4 | head -n1)
if [[ -z "${MONITOR_TS_IP}" ]]; then
  echo "ERROR: Could not determine Tailscale IPv4. Is tailscale running?"
  exit 1
fi

# ── 1. .env: create interactively on first run, load on subsequent runs ───────

if [[ ! -f .env ]]; then
  echo "========================================"
  echo "  First-time setup — configure .env"
  echo "========================================"
  echo ""

  ask TZ            "Timezone for all containers"              "Asia/Shanghai"
  ask GF_ADMIN_USER "Grafana admin username"                   "admin"
  ask_secret GF_ADMIN_PASSWORD "Grafana admin password"
  ask DOMAIN        "Grafana public domain (e.g. monitor.example.com)"
  ask PROMETHEUS_RETENTION "Prometheus data retention"         "30d"
  ask LOKI_MODE     "Loki mode: embedded or external"          "external"
  ask LOKI_RETENTION "Loki retention when embedded"            "336h"

  if [[ "$LOKI_MODE" == "embedded" ]]; then
    LOKI_URL="http://${MONITOR_TS_IP}:3100"
  elif [[ "$LOKI_MODE" == "external" ]]; then
    ask LOKI_URL "External Loki URL (e.g. http://100.x.y.z:3100)"
  else
    echo "ERROR: LOKI_MODE must be 'embedded' or 'external'."
    exit 1
  fi

  echo ""
  write_env
  echo ""
else
  echo "==> Loading existing .env"
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a

  set_env_value MONITOR_TS_IP "$MONITOR_TS_IP"

  if [[ -z "${LOKI_MODE:-}" ]]; then
    ask LOKI_MODE "Loki mode: embedded or external" "external"
    set_env_value LOKI_MODE "$LOKI_MODE"
  fi

  if [[ -z "${LOKI_RETENTION:-}" ]]; then
    LOKI_RETENTION="336h"
    set_env_value LOKI_RETENTION "$LOKI_RETENTION"
  fi

  if [[ "${LOKI_MODE}" == "embedded" ]]; then
    LOKI_URL="http://${MONITOR_TS_IP}:3100"
    set_env_value LOKI_URL "$LOKI_URL"
  elif [[ "${LOKI_MODE}" == "external" ]]; then
    if [[ -z "${LOKI_URL:-}" || "${LOKI_URL}" == *"100.x.x.x"* ]]; then
      ask LOKI_URL "External Loki URL (e.g. http://100.x.y.z:3100)"
      set_env_value LOKI_URL "$LOKI_URL"
    fi
  else
    echo "ERROR: LOKI_MODE must be 'embedded' or 'external'."
    exit 1
  fi

  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

# ── 2. Runtime data directories ───────────────────────────────────────────────
echo "==> Creating runtime data directories..."
mkdir -p data/prometheus data/alertmanager grafana/data
if [[ "${LOKI_MODE}" == "embedded" ]]; then
  mkdir -p data/loki
fi

echo "==> Fixing Grafana data directory permissions (UID 472)..."
sudo chown -R 472:472 grafana/data
sudo chmod -R u+rwX grafana/data

# ── 3. Prometheus target files ────────────────────────────────────────────────
echo "==> Generating Prometheus target files..."
chmod +x gen-targets.sh
./gen-targets.sh

# ── 4. Done ───────────────────────────────────────────────────────────────────
echo ""
echo "==> Setup complete. Next steps:"
echo ""
echo "    1. Edit servers.txt — add your Tailscale nodes"
echo "    2. Edit probes/http_targets.txt, icmp_targets.txt, tcp_targets.txt"
echo "       then re-run: ./gen-targets.sh"
echo "    3. Configure Nginx using the example in nginx/monitor.conf"
echo "       Replace 'monitor.example.com' with your actual domain"
if [[ "${LOKI_MODE}" == "embedded" ]]; then
  echo "    4. Run: docker compose --profile loki up -d"
else
  echo "    4. Run: docker compose up -d"
fi
echo "    5. Verify Loki: curl -fsS ${LOKI_URL}/ready"
echo "    6. Run: docker exec prometheus promtool check config /etc/prometheus/prometheus.yml"
