apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: ${LOKI_URL}
    isDefault: false
    editable: true
    jsonData:
      timeout: 60
      maxLines: 1000
